spring.application.name=OauthTwo

spring.security.oauth2.client.registration.github.client-id=Iv23lissvHez0wFcQT5A
spring.security.oauth2.client.registration.github.client-secret=f1172fab552bc0dde7a1156436688d0f8b65781d